### ISSUE TITLE
Adicionar página para convidados

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/opendataday#7]
Teremos diferentes convidados (em torno de 10). Devemos ter uma página para mostrar uma foto deles, com descrição curta (um tweet) e onde vai participar (se mesa, hackathon etc).

**Comment by angelocl** [comment]
**Abertura**

Evandro do Nascimento, reitor da Universidade Estadual de Feira de Santana - UEFS
Evandro do Nascimento Silva possui graduação em Ciências Biológicas e também o mestrado em Ciências Biológicas, pela Universidade Federal da Paraíba, e doutorado pela Universidade de Michigan, EUA. Atualmente é Professor Titular do Departamento de Ciências Biológicas da Uefs e foi reeleito para o cargo de reitor.

Fernanda Campagnucci, diretora da Open Knowledge Brasil: "Dados abertos para uma cidade democrática e inteligente"
Diretora-executiva da Open Knowledge Brasil, organização da sociedade civil que atua para democratizar o acesso a dados e ampliar a transparência e a participação política com o uso de tecnologias cívicas. Integrou a carreira de gestão pública na Prefeitura de São Paulo, onde foi responsável pela política de transparência e integridade, além de ter coordenado projetos de inovação e governo aberto como o Pátio Digital. Graduada em Jornalismo e mestre em Educação, é doutoranda em Administração Pública pela FGV-SP. 

**Mesa Redonda I - Transparência como Política Pública**

Amanda Faria Lima, Co-fundadora da Instituto de Governo Aberto - IGA: "Transparência para defesa de direitos"
Apaixonada e atuante pelo governo aberto, transparência e promoção da integridade pública. Internacionalista pela UFABC e Especialista em Gestão Pública pelo INSPER. Já atuei no setor público, na Controladoria Geral do Município de São Paulo, com governo aberto, transparência e acesso à informação. Sou cofundadora do Instituto de Governo Aberto - IGA e presto consultoria em integridade socioambiental, conectando o combate à corrupção à promoção da preservação ambiental.

George Santiago, Observatório Social de Santo Antônio de Jesus: "Estratégias para estimular a divulgação de Dados Abertos pela  Administração Pública"
Membro do Observatório Social de Santo Antônio de Jesus. Assessor do Ministério Público de Contas que atua junto ao Tribunal de Contas do Estado da Bahia. Moderador do Grupo "Dados Abertos .Br". Graduação em Direito – Universidade Federal da Bahia (UFBA); Graduando em Ciências Contábeis – UFBA; Curso de formação em Ciência de Dados pela Data Science Academy .

Rafael Velame, Blog do Velame / Dados Abertos de Feira: "Transparência em Feira "
Formado em Comunicação Social - Habilitação em Jornalismo. Online desde 2000, fundador do Portal FSonline, Bahiagora, Blog da Feira e Blog do Velame. Estudou Redes Sociais, Colaboração e Mobilidade na PUC-SP, Marketing Político e Campanhas Eleitorais na PUC-SP e Comunicação Empresarial na ESPM-SP. Atuou entre 2017 e 2020 como âncora do Café das 6 na Rádio Globo. Autor do livro Palanque Offline. 

Jonathas Monteiro, Vereador em Feira de Santana e Professor da Rede Estadual de Ensino


**Mesa Redonda II - Ciência Aberta**

Luana Farias Sales Marques, Arquivo Nacional / PPGCI IBICT-UFRJ / GoFAIR BRASIL: "Compartilhamento de Dados de pesquisa para o avanço da Ciência"
Doutora em Ciência da Informação pelo Programa de Pós-Graduação do IBICT/UFRJ (2011-2014). Mestre em Ciência da Informação pelo convênio UFF/IBICT (2004-2006), Graduação em Biblioteconomia e Documentação pela Universidade Federal Fluminense (2003). Bolsista de Produtividade Pq2. Atuou como  Analista em C & T da CNEN, no Instituto de Engenharia Nuclear, participando da criação da linha de pesquisa de Gestão do Conhecimento Nuclear. Atualmente exerce o cargo de Coordenadora Geral de Acesso e Difusão de Acervos do Arquivo Nacional. É Analista em C & T do MCTIC/IBICT, atuando como docente do Programa de Pós-graduação em Ciência da Informação do convênio IBICT-UFRJ e Coordenadora da Rede de Implementação do GO FAIR Brasil. 

Bethania de A. Almeida, Analista da FIOCRUZ/CIDACS: "Dados para Pesquisa em Saúde Pública na Perspectiva da Ciência Aberta"
Bethânia Almeida é socióloga com doutorado em saúde pública. Servidora da FIOCRUZ atua no Centro de Integração de Dados e Conhecimentos para Saúde (CIDACS) e em outras iniciativas institucionais como o Grupo de Trabalho em Ciência Aberta. Possui experiência em gestão científica, tecnológica e da inovação, e na condução e coordenação de pesquisas. Dentre as suas áreas de interesse estão a governança de dados para pesquisa na área da saúde pública e a sociologia da ciência intensiva no uso de dados.

Washington Franca-Rocha, Professor da UEFS : "Geoportais: Geoinformação com dados abertos"
Professor Titular da Universidade Estadual de Feira de Santana (UEFS) e professor efetivo do Programa de Pós Graduação em Ciências da Terra e do Ambiente da UEFS, atuando em Modelagem Geospacial e Inteligência Geográfica. Coordena as equipe dos Geoportais MAPBIOMAS CAATINGA, MAPBIOMAS ARIDA, GEOCOVID e Portal Agro Bahia.

Rodrigo Tripodi Calumby, Professor da UEFS: "Dados Abertos e Ciência de Dados"
Bacharel, Mestre e Doutor em Ciência da Computação. Professor nas áreas de Mineração de Dados e Machine Learning da Universidade Estadual de Feira de Santana (UEFS) e docente do Programa de Pós-Graduação em Ciência da Computação (PGCC/UEFS). Seus principais interesses de pesquisa incluem: Ciência de Dados, Recuperação da Informação, Classificação de Dados Multimídia, Fusão de Dados, Aprendizado de Máquina, Recuperação Interativa e Computação Aplicada à Saúde.

**Comment by anapaulagomes** [comment]
Feito: https://dadosabertosdefeira.github.io/opendataday/#resources
